import "./globals.css";

import type { Metadata } from "next";
import React from "react";
import { Toaster } from "sonner";

import ClientShell from "@/components/layout/ClientShell";

export const metadata: Metadata = {
  title: "StudAI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body className="h-screen w-screen overflow-hidden flex flex-col">
        <ClientShell>{children}</ClientShell>
        <Toaster />
      </body>
    </html>
  );
}
