import "./globals.css";

import type { Metadata } from "next";
import React from "react";

import NavBar from "@/components/layout/navMenu/NavBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div>
          <NavBar />
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
