import "./globals.css";

import type { Metadata } from "next";

import AsideNav from "@/components/layout/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-bt">
      <body>
        <div>
          <nav>
            <AsideNav />
          </nav>
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
