services:
  frontend:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: frontend_app
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: npm run dev
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
