version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: frontend_app
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: npm run dev
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000

  backend:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    container_name: backend_app
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    networks:
      - app-network
    restart: unless-stopped
    env_file:
      - ./backend/.env

networks:
  app-network:
    driver: bridge
